name: weather_watch
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  darksky_weather: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - assets/images/foggy.jpg
  - assets/images/rain.jpg
  - assets/images/snow.jpg
  - assets/images/sunny.jpg
  - assets/images/thunder.jpg
  - assets/images/windy.jpg

  fonts:
  - family: WeatherIcon
    fonts:
      - asset: assets/fonts/WeatherIcon.ttf
